### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by kenumir** [kenumir/Pinger#9]
Stack trace:

> Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
>        at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1842)
>        at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1860)
>        at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:650)
>        at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:609)
>        at com.wt.pinger.activity.MainActivity$1.onTabSelected(MainActivity.java:71)
>        at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.updateItems(AHBottomNavigation.java:598)
>        at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.access$000(AHBottomNavigation.java:52)
>        at com.aurelhubert.ahbottomnavigation.AHBottomNavigation$2.onClick(AHBottomNavigation.java:443)
>        at android.view.View.performClick(View.java:4789)
>        at android.view.View$PerformClick.run(View.java:19881)
>        at android.os.Handler.handleCallback(Handler.java:739)
>        at android.os.Handler.dispatchMessage(Handler.java:95)
>        at android.os.Looper.loop(Looper.java:135)
>        at android.app.ActivityThread.main(ActivityThread.java:5294)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at java.lang.reflect.Method.invoke(Method.java:372)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

Version: 3.2.0 (67)

**Comment by AhmadullahSaikat** [comment]
try {
            transaction.commit();
        } catch (IllegalStateException e) {
            transaction.commitAllowingStateLoss();
        }

**Comment by gokhan47** [comment]
why would you commit the transaction with stateLoss chance? unless you need saveInstance
